SQUARE_TILE = 1
TILE_AS_MAIN_IMAGE = 2

DEFAULT_SQUARE_TILE_SIZE = 20
TILES_PER_IMAGE_DIMENSION = 50

USE_BUILTIN_TILE_IMAGES = True
COLUMNS_NUMBER = None
ROWS_NUMBER = None
NAME = 'mosaic'
IMAGE_FORMAT = 'png'
APPLY_SEPIA = True
APPLY_GREYSCALE = False
