SQUARE_TILE = 1
TILE_AS_MAIN_IMAGE = 2

DEFAULT_OPTION = SQUARE_TILE

DEFAULT_SQUARE_TILE_SIZE = 20
DEFAULT_TILES_PER_IMAGE_DIMENSION = 50

USE_BUILTIN_TILE_IMAGES = True
DEFAULT_COLUMNS_NUMBER = None
DEFAULT_ROWS_NUMBER = None
DEFAULT_NAME = 'mosaic'
DEFAULT_IMAGE_FORMAT = 'png'
APPLY_SEPIA = False
APPLY_GREYSCALE = False
DEFAULT_ENLARGEMENT = 1
